### ISSUE TITLE
Model the scene

### ISSUE THREAD

**Issue by dserafim1999** [dserafim1999/CG-Project-2#1]
- Walls;
- Canons (add rotation);
- Ball (multiple);

**Comment by OuuGiii** [comment]
Hello, @dserafim1999 :)

You can add the commits that belongs to this issue by opening the commit(s) and commenting the issue number like this "#1" to the commit :) Otherwise in the commit message you can already add the "#1" then it will automatically know that which commits belongs to which issues.
